[workspace]

members = [
    "primitives",
    "layer_model",
    "layer_animator",
    "layer_renderer",
    "layer_compositor",
    "wgpu_surface",
    "scene_controller",
    "examples/dev_shell",
    "examples/key_move",
]
