[workspace]

members = [
    "logic",
    "animator",
    "compositor",
    "wgpu_renderer",
    "scheduler",
    "primitives",
    "painter",
    "applications/dev_shell",
    "applications/key_move",
]
