[package]
name = "compositor"
version = "0.1.0"
authors = ["seungha"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raqote = "0.8.0"
euclid = "0.22.1"